version: '3'

services:
  postgres:
    profiles: ["postgres"]
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=mypass
      - POSTGRES_DB=jaffle_shop
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  dbt:
    profiles: [ "default" ]
    image: ghcr.io/dbt-labs/dbt-postgres:1.5.8
    environment:
      - DBT_PROFILES_DIR=/usr/app
    volumes:
      - .:/usr/app